/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package CarRace;

import com.sun.awt.AWTUtilities;
import java.awt.BasicStroke;
import java.awt.Color;
import java.io.File;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import static javax.swing.JOptionPane.PLAIN_MESSAGE;
import javax.swing.UIManager.LookAndFeelInfo;
import javax.swing.border.*;

/**
 *
 * @author Sagar
 */
public class CarRaceMenu extends javax.swing.JFrame {

    /**
     * Creates new form Menu
     */
    public CarRaceMenu() {
        initComponents();
        this.getRootPane().setBorder(new LineBorder(Color.LIGHT_GRAY,Color.TRANSLUCENT));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel4 = new javax.swing.JPanel();
        start = new javax.swing.JButton();
        highscore = new javax.swing.JButton();
        exit = new javax.swing.JButton();
        instruction = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Wars of the Cars");
        setMaximumSize(new java.awt.Dimension(1280, 627));
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(1280, 627));
        setResizable(false);
        getContentPane().setLayout(null);

        jPanel4.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(0, 0, 0)));
        jPanel4.setMaximumSize(new java.awt.Dimension(1280, 720));
        jPanel4.setMinimumSize(new java.awt.Dimension(1280, 627));
        jPanel4.setLayout(null);

        start.setText("START GAME");
        start.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        start.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                startActionPerformed(evt);
            }
        });
        jPanel4.add(start);
        start.setBounds(60, 130, 210, 40);

        highscore.setText("HIGHSCORES");
        highscore.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        highscore.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                highscoreActionPerformed(evt);
            }
        });
        jPanel4.add(highscore);
        highscore.setBounds(60, 340, 210, 40);

        exit.setText("EXIT");
        exit.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitActionPerformed(evt);
            }
        });
        jPanel4.add(exit);
        exit.setBounds(60, 440, 210, 40);

        instruction.setText("INSTRUCTIONS");
        instruction.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        instruction.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                instructionActionPerformed(evt);
            }
        });
        jPanel4.add(instruction);
        instruction.setBounds(60, 230, 210, 40);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/CarRace/carwars1.png"))); // NOI18N
        jPanel4.add(jLabel2);
        jLabel2.setBounds(0, 0, 1280, 627);

        getContentPane().add(jPanel4);
        jPanel4.setBounds(0, 0, 1440, 710);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void startActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_startActionPerformed
        // TODO add your handling code here:
        new Game();
    }//GEN-LAST:event_startActionPerformed

    private void highscoreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_highscoreActionPerformed
        // TODO add your handling code here:
        new Highscore().main(new String[1]);
    }//GEN-LAST:event_highscoreActionPerformed

    private void exitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_exitActionPerformed

    private void instructionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_instructionActionPerformed
        // TODO add your handling code here:
        new Instructions().main(new String[1]);
    }//GEN-LAST:event_instructionActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CarRaceMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CarRaceMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CarRaceMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CarRaceMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                CarRaceMenu me=new CarRaceMenu();
                me.setLocationRelativeTo(null);
                me.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton exit;
    private javax.swing.JButton highscore;
    private javax.swing.JButton instruction;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JButton start;
    // End of variables declaration//GEN-END:variables
}
